// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase configuration for Web
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAAQZNlxV9Rtjzj6ImdIQ0rSKARCjb6U3g",
      authDomain: "igit-aca-f8d86.firebaseapp.com",
      projectId: "igit-aca-f8d86",
      storageBucket: "igit-aca-f8d86.firebasestorage.app",
      messagingSenderId: "722495505334",
      appId: "1:722495505334:web:f4614b2d2c69c64356f717",
      measurementId: "G-XJ82NNLMLV");

  // Firebase configuration for Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg9dXyBQ1m4DKzOOO7WLK8Kwu8vPzFxgc',
    appId: '1:722495505334:android:070b8aff8a009b5756f717',
    messagingSenderId: '722495505334',
    projectId: 'igit-aca-f8d86',
    storageBucket: 'igit-aca-f8d86.firebasestorage.app',
  );

  // Firebase configuration for Windows
  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: "AIzaSyAAQZNlxV9Rtjzj6ImdIQ0rSKARCjb6U3g",
      authDomain: "igit-aca-f8d86.firebaseapp.com",
      projectId: "igit-aca-f8d86",
      storageBucket: "igit-aca-f8d86.firebasestorage.app",
      messagingSenderId: "722495505334",
      appId: "1:722495505334:web:853fb064a7a6e1a656f717",
      measurementId: "G-3X9D6Z9HYG");
}
